### PR TITLE
Create python3_Esha.py

### PR DESCRIPTION
**Pull request by eshah122**

### CODE REVIEW

**Comment by eshah122** [comment]
December 17th solution

**Comment by Deepika-Govindaswamy** [comment]
Hi Hope you're doing well.
Thank you for taking the time to solve the all the questions. We really appreciate your efforts. We will verify your submission and your certificate will be sent to you in your email. Thank you for participating. Keep an eye on our social media page for our upcoming events.
Can you please specify your college/institution name and your mail for the certificate.

**Comment by Deepika-Govindaswamy** [comment]
Also kindly specify your full name for the certificates.

**Comment by eshah122** [comment]
Name:  Esha H
Email : ***@***.***
Institution: PES UNIVERSITY




Thanks & Regards
Esha

**Comment by Deepika-Govindaswamy** [comment]
Hi,
There has been some issue in contacting you via mail. Can you please share the following details to the specified mail Id.
Full name, college/institution name and your mail id.
Share the details to acm.svcecse@gmail.com

**Comment by eshah122** [comment]
I have sent


Thanks
Esha

**Pull request merged**
