### PR TITLE
22-days submission I made

### PR DESCRIPTION
**Pull request by yesdhruv**
Status of the Questions:
✔️ December 1 - William Butcher's Mission
✔️ December 2 - The Secret Language
✔️ December 3 - Minesweeper
✔️ December 4 - Industry
✔️ December 5 - Don’t let Mason misspend!
✔️ December 6 - Swapped
✔️ December 7 - Word Map
✔️ December 8 - Aptitude Check!
✔️ December 9 - Kochouseph Konundrum!
✔️ December 10 - Play with words
✔️ December 11 - Monkey jump
✔️ December 12 - Shez in a Maze!
✔️ December 13 - The Labyrinth
✔️ December 14 - Math Mystery
✔️ December 15 - The Murderers Meet
✔️ December 16 - H2O Receptacle
✔️ December 17 - Zig Zag Conversion
✔️ December 18 - Find the way
✔️ December 19 - Hidden Anagram
✔️ December 20 - Code a Subsequence
✔️ December 21 - The Devil Towers
✔️ December 22 - The Markowitz Paradox
❌ December 23 - Meeting Rooms
❌ December 24 - Cracking The Safe
❌ December 25 - The Motorbike Race
❌ December 26 - Circulate
❌ December 27 - Mission to Earth: Re-Calibrated
❌ December 28 - The Journey to the Eternal Engine
❌ December 29 - Candies
❌ December 30 - Precise Portion
❌ December 31 - The Quad of Queens

### CODE REVIEW

**Comment by yesdhruv** [comment]
@neha2127 Merge the PR

**Comment by Deepika-Govindaswamy** [comment]
Hi Hope you're doing well.
Thank you for taking the time to solve the all the questions. We really appreciate your efforts. We will verify your submission and your certificate will be sent to you in your email. Thank you for participating. Keep an eye on our social media page for our upcoming events.
Can you please specify your college/institution name and your mail for the certificate.

**Comment by Deepika-Govindaswamy** [comment]
Also kindly specify your full name for the certificates.

**Comment by yesdhruv** [comment]
Thank you for organising such events.
Name-Dhruv Rawat
College: Maharaja Surajmal Institute of Technology, New Delhi
e-mail: [dhruvrawat54@gmail.com](mailto:dhruvrawat54@gmail.com)

**Pull request merged**
