### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by hrajput0322**
December2 solution

### CODE REVIEW

**Comment by Deepika-Govindaswamy** [comment]
Hi Hope you're doing well.
Thank you for taking the time to solve the all the questions. We really appreciate your efforts. We will verify your submission and your certificate will be sent to you in your email. Thank you for participating. Keep an eye on our social media page for our upcoming events.
Can you please specify your college/institution name and your mail for the certificate.

**Comment by hrajput0322** [comment]
College : Indian Institute of Information Technology, Guwahati.
Mail : ***@***.***

**Comment by Deepika-Govindaswamy** [comment]
Also kindly specify your full name for the certificates.

**Comment by Deepika-Govindaswamy** [comment]
Hi,
There has been some issue in contacting you via mail. Can you please share the following details to the specified mail Id.
Full name, college/institution name and your mail id.
Share the details to acm.svcecse@gmail.com

**Pull request merged**
